openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'component-influx'
  description: 'influx copmponent API'

servers:
  - description: IoToad API endpoint
    url: https://iotoad.org/api/out/influx
    
paths:
  /{measurement}:
    get:
      summary: Send write/update request to Agent
      operationId: outRequest
      parameters:
        - name: measurement
          in: path
          description: Measurement type that is being queried. 
          required: true
          schema:
            type: string
            pattern: "[^/]+"
            example: "power"
        - name: operation
          in: query
          required: false
          schema:
            type: string
            enum: [count, distinct, integral, mean, median, mode, spread, stddev, sum, bottom, first, last, max, min, percentile, sample, top]
          description: "Aggregations and Selectors that can be used when querying. For more information check the following url: https://docs.influxdata.com/influxdb/v1.7/query_language/functions/"
        - name: id
          in: query
          required: false
          schema:
            type: string
            example: sp_r0c2
          description: Device ID
        - name: type
          in: query
          required: false
          schema:
            type: string
            enum: [w, g, p]
          description: "Device type: w (Workstation), g (Group Room) or p (Printer)"
        - name: row
          in: query
          required: false
          schema:
            type: integer
            nullable: true
            example: 1    
          description: Device row. It is nullable, if it has no row
        - name: column
          in: query
          required: false
          schema:
            type: integer
            nullable: true
            example: 1    
          description: Device column. It is nullable, if it has no column
        - name: from
          in: query
          required: false
          schema:
            type: number
            format: double
            example: 12345678
          description: Time lower limit of the data that is being retrieved (POSIX seconds)
        - name: to
          in: query
          required: false
          schema:
            type: number
            format: double
            example: 12345678
          description: Time upper limit of the data that is being retrieved (POSIX seconds)
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OutObject'
        '405':
          description: Invalid input
        
components:
  schemas:
    OutObject:
      type: array
      items:
        type: object
        properties:
          e:
            $ref: '#/components/schemas/EventObject'
          bn:
            type: string
            description: URI path concatenating the Device ID and the type of resource. 'deviceID/resourceType'
            example: "sp_r3c4/power"
          bu:
            type: string
            description: Resource unit
            example: "W"
      
    EventObject:
      type: array
      items:
        type: object
        properties:
          v:
            type: number
            format: float
            description: Value
            example: 40.2
          t:
            type: number
            format: double
            description: POSIX seconds (seconds since the epoch)
            example: 12345678